In [20]:
# numpy = numrical python 
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([11,12,13,14,15,16,17,18,19,20])
c=a+b
print(c)

[12 14 16 18 20 22 24 26 28 30]


In [4]:
d=[44,55]
e=[44,55]
k=d+e
print(k) 
#  it add to list to make one list

[44, 55, 44, 55]


In [3]:
import numpy as np
st = [[1,2,3],[1,2,3],[1,2,3]]
starr=np.array(st)
print(starr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
starr.dtype

dtype('int32')

In [11]:
print(type(starr))

<class 'numpy.ndarray'>


In [11]:
num=[]
for i  in range(11):
    num.append(i)
print(num)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
num_np=np.arange(11)
print(num_np)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
np.arange(345,555,7)


array([345, 352, 359, 366, 373, 380, 387, 394, 401, 408, 415, 422, 429,
       436, 443, 450, 457, 464, 471, 478, 485, 492, 499, 506, 513, 520,
       527, 534, 541, 548])

In [15]:
np.arange(500,100,-55)

array([500, 445, 390, 335, 280, 225, 170, 115])

In [54]:
num_lst=[i**2 for i in range(0,11)]
print(num_lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [58]:
m=(k*2 for k in range(4,11))
print(m)

<generator object <genexpr> at 0x044046F0>


In [31]:
z = np.arange(10000)
z=z**3
%timeit z

44.4 ns ± 5.54 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [21]:
c = range(1000)
%timeit[i**3 for i in c]

585 µs ± 114 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [37]:
np.random.random(10)

array([0.54330404, 0.34633238, 0.84808148, 0.77190672, 0.85302529,
       0.90854012, 0.56207503, 0.49187841, 0.08183617, 0.11929669])

In [40]:
u=np.array([1,2,3,4])
u

array([1, 2, 3, 4])

In [45]:
np.ones((3,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
# float matrix
np.zeros((1,1))




array([[0]])

In [72]:
# int marix
np.zeros((1,1),dtype=np.int32)

array([[0]])

In [73]:
# 1 dimesion vector float type
np.zeros(1)

array([0.])

In [74]:
# 1 dimension vector
np.zeros(1, dtype=np.int32 )

array([0])

In [79]:
np.ones((2,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [86]:
# for identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [88]:
np.full((3,3),6.12)

array([[6.12, 6.12, 6.12],
       [6.12, 6.12, 6.12],
       [6.12, 6.12, 6.12]])

In [89]:
np.diag([3,11,9])

array([[ 3,  0,  0],
       [ 0, 11,  0],
       [ 0,  0,  9]])

In [91]:
x=np.diag(np.arange(1,99))
x

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  2,  0, ...,  0,  0,  0],
       [ 0,  0,  3, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 96,  0,  0],
       [ 0,  0,  0, ...,  0, 97,  0],
       [ 0,  0,  0, ...,  0,  0, 98]])

In [92]:
b=np.array([6,6,93])
print(b)
np.tile(b,(3,3))
# staks

[ 6  6 93]


array([[ 6,  6, 93,  6,  6, 93,  6,  6, 93],
       [ 6,  6, 93,  6,  6, 93,  6,  6, 93],
       [ 6,  6, 93,  6,  6, 93,  6,  6, 93]])

In [99]:
np.random.seed(555)
print(np.random.random())
print(np.random.random())

0.7178340874802498
0.047855132556195557


In [104]:
k=np.random.random((4,4))
rounded=np.round(k,2)
rounded

array([[0.41, 0.79, 0.37, 0.22],
       [0.31, 0.29, 0.15, 0.74],
       [0.79, 0.33, 0.06, 0.97],
       [0.03, 0.79, 0.02, 0.16]])

In [107]:
new=rounded*1000
new

array([[410., 790., 370., 220.],
       [310., 290., 150., 740.],
       [790., 330.,  60., 970.],
       [ 30., 790.,  20., 160.]])

In [109]:
intt=new.astype(np.int32)
intt

array([[410, 790, 370, 220],
       [310, 290, 150, 740],
       [790, 330,  60, 970],
       [ 30, 790,  20, 160]])

In [110]:
a=np.arange(10)
print(a.dtype)
print(a)

int32
[0 1 2 3 4 5 6 7 8 9]


In [111]:
a.itemsize

4